---
- name: "SETUP PREFIXES for {{ inventory_hostname}}"
  delegate_to: localhost
  netbox.netbox.netbox_prefix:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: "{{ prefix.prefix }}"
      vrf: "{{ prefix.vrf }}"
    state: present
  loop: "{{ fabric_device_prefixes | default([])}}"
  loop_control:
    loop_var: prefix
    label: "{{ prefix['prefix'] }}"
  ignore_errors: yes

- name: "ADD FABRIC INTERFACES TO NETBOX for {{ inventory_hostname}}"
  delegate_to: localhost
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device: "{{ fabric_interface.device }}"
      name: "{{ fabric_interface.name }}"
      type: "{{ fabric_interface.form_factor }}"
      mgmt_only: True
    state: present
  loop: "{{ fabric_interfaces_hw | default([])}}"
  loop_control:
    loop_var: fabric_interface
    label: "{{ fabric_interface['name'] }}"
  ignore_errors: yes

- name: "ADD IP ADDRESS TO FABRIC INTERFACE IN NETBOX for {{ inventory_hostname}}"
  delegate_to: localhost
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ entry.address }}"
      vrf: "{{ entry.vrf }}"
      assigned_object:
        name: "{{ entry.assigned_object.name }}"
        device: "{{ entry.assigned_object.device }}"
    state: present
  loop: "{{ fabric_interface_ips | default([])}}"
  loop_control:
    loop_var: entry
    label: "{{ entry['address'] }}"
  ignore_errors: yes
