---
- name: "TASK 10: SETUP SITES"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data: "{{ item }}"
    state: present
  loop: "{{ site_list }}"

- name: "TASK 20: SETUP MANUFACTURERS"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_manufacturer:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ manufacturer }}"
    state: present
  loop: "{{ manufacturers }}"
  loop_control:
    loop_var: manufacturer

- name: "TASK 30: SETUP DEVICE TYPES"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_device_type:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      model: "{{ device_type.model }}"
      manufacturer: "{{ device_type.manufacturer }}"
      slug: "{{ device_type.slug }}"
      part_number: "{{ device_type.part_number }}"
      is_full_depth: "{{ device_type.full_depth }}"
    state: present
  loop: "{{ device_types }}"
  loop_control:
    loop_var: device_type
    label: "{{ device_type['model'] }}"

- name: "TASK 40: SETUP PLATFORMS"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_platform:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ platform.name }}"
      slug: "{{ platform.slug }}"
    state: present
  loop: "{{ platforms }}"
  loop_control:
    loop_var: platform
    label: "{{ platform['name'] }}"

- name: "TASK 50: SETUP DEVICE ROLES"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_device_role:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ role.name }}"
      slug: "{{ role.slug }}"
      color: "{{ role.color }}"
    state: present
  loop: "{{ device_roles }}"
  loop_control:
    loop_var: role
    label: "{{ role['name'] }}"

- name: "TASK 60: SETUP MANAGEMENT VRF"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_vrf:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ vrf.name }}"
      enforce_unique: true
      description: "{{ vrf.description }}"
    state: present
  loop: "{{ vrfs }}"
  loop_control:
    loop_var: vrf
    label: "{{ vrf['name'] }}"

- name: "TASK 70: SETUP MANAGEMENT PREFIXES"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_prefix:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      prefix: "{{ prefix.prefix }}"
      vrf: "{{ prefix.vrf }}"
      description: "{{ prefix.description }}"
    state: present
  loop: "{{ prefixes }}"
  loop_control:
    loop_var: prefix
    label: "{{ prefix['prefix'] }}"

- name: "TASK 100: NETBOX >> ADD DEVICE TO NETBOX"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ device.name }}"
      device_type: "{{ device.device_type }}"
      platform: "{{ device.platform }}"
      status: "{{ device.status }}"
      device_role: "{{ device.device_role }}"
      site: "{{ device.site }}"
      serial: "{{ device.serial }}"
      # custom_fields:
      #   code_version: "{{ ansible_facts['net_version'] }}"
    state: present
  loop: "{{ devices }}"
  loop_control:
    loop_var: device
    label: "{{ device['name'] }}"

- name: "TASK 110: NETBOX >> ADD INTERFACES TO NETBOX"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device: "{{ device.name }}"
      name: "{{ device.management_name }}"
      type: "{{ device.management_form_factor }}"
      mgmt_only: True
    state: present
  loop: "{{ devices }}"
  loop_control:
    loop_var: device
    label: "{{ device['name'] }}"

- name: "TASK 120: NETBOX >> ADD IP ADDRESS TO MANAGEMENT INTERFACE IN NETBOX"
  delegate_to: localhost
  ignore_errors: yes
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ entry.address }}"
      vrf: "{{ entry.vrf }}"
      assigned_object:
        name: "{{ entry.assigned_object.name }}"
        device: "{{ entry.assigned_object.device }}"
    state: present
  loop: "{{ management_ips }}"
  loop_control:
    loop_var: entry
    label: "{{ entry['address'] }}"
