---
### AVD Default settings
# Root directory where to build output structure
root_dir: '{{inventory_dir}}'

### Netbox Access configuration
netbox_url: 'http://10.83.28.163:31062'
netbox_token: "keO49sqSPMfIHLWWgGvOg6F0wJZWTN4hJA9IV80g"
netbox_state: present

### Netbox default entries

# Default
mgmt_vrf: MGMT
mgmt_interface: "Management1"

# defaults file for eos_netbox_provisioner
site_list:
  - name: Paris
    time_zone: Europe/Paris
    status: Active
  - name: Marseille
    time_zone: Europe/Paris
    status: Active
  - name: Lyon
    time_zone: Europe/Paris
    status: Active
  - name: Toulouse
    time_zone: Europe/Paris
    status: Active

manufacturers:  # In alphabetical order
  - Arista

device_types:
  - model: "vEOS-LAB"
    manufacturer: "Arista"
    slug: "veos-lab"
    part_number: "veos-lab"
    full_depth: False
  - model: "DCS-7050X3"
    manufacturer: "Arista"
    slug: "dcs-7050x3"
    part_number: "dcs-7050x3"
    full_depth: True

platforms:
  - name: "EOS"
    slug: "eos"
  - name: "vEOS"
    slug: "veos"

device_roles:
  - name: 'spine'
    slug: spine
    color: 6b8e23
  - name: 'leaf'
    slug: leaf
    color: 6b8e23
  - name: 'l2leaf'
    slug: l2leaf
    color: 6b8e23
